# Generated by Django 5.0.6 on 2024-06-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Image',
            field=models.ImageField(upload_to='blog/'),
        ),
    ]
